window.I18N_DATA = {
  'zh-CN': {
    pageTitle: 'Minimal Tab',
    searchPlaceholder: '输入搜索内容...',
    settingsTitle: '设置',
    settingsHeader: '设置',

    navTheme: '主题/壁纸',
    navEngines: '搜索功能',
    navPersonalize: '个性化',
    navAbout: '关于',
    navMore: '更多设置',
    aboutVersion: 'Version',
    aboutProject: '项目地址',
    aboutFeedback: '问题反馈',
    aboutPrivacy: '隐私政策',
    aboutLicense: '遵循 MIT 开源协议',
    colorPicker: '取色器',

    sectionAppearance: '整体外观',
    themeSystem: '系统',
    themeLight: '浅色',
    themeDark: '深色',
    sectionAccentColor: '主题色',
    sectionWallpaper: '壁纸',

    wallpaperOverlay: '壁纸遮罩',
    wallpaperBlur: '壁纸模糊',
    wallpaperRotate: '壁纸轮换',
    rotateNow: '立即轮换',
    rotateOff: '不进行轮换',
    rotate1h: '每 1 小时轮换',
    rotate6h: '每 6 小时轮换',
    rotate12h: '每 12 小时轮换',
    rotate24h: '每 24 小时轮换',

    sectionSidebar: '侧边栏',
    sectionClock: '时钟',
    clockColor: '时钟颜色',
    sidebarOpacity: '透明度',
    sidebarFrosted: '毛玻璃',
    digitalClock: '数字时钟',
    followSearch: '跟随搜索框',
    clockPosition: '时钟位置',
    clockBelow: '搜索框下方',
    clockAbove: '搜索框上方',
    clockLeftTop: '左上',
    clockRightTop: '右上',
    clockCenter: '居中',
    clockLeftBottom: '左下',
    clockRightBottom: '右下',
    clockCustom: '自定义',
    clockCustomX: 'X',
    clockCustomY: 'Y',
    sectionLanguage: '语言偏好',

    sectionSearchBox: '搜索框',
    enableSearchBox: '启用搜索框',
    searchOffsetY: '垂直偏移',
    searchOffsetX: '水平偏移',
    searchWidth: '搜索框宽度',
    searchRadius: '搜索框圆角',
    sectionEngines: '搜索引擎',
    sectionDefaultEngine: '默认引擎',
    searchHistory: '搜索历史',
    openInNewTab: '在新标签页中打开搜索结果',
    suggestionProvider: '搜索建议接口',
    suggestionOff: '不使用',
    suggestionBaidu: '百度',
    suggestionGoogle: 'Google',
    suggestionBing: '必应',
    suggestionTitle: '搜索建议',

    addCustomEngine: '添加自定义搜索引擎',
    editCustomEngine: '编辑自定义搜索引擎',
    ceName: '名称',
    ceNamePlaceholder: '搜索引擎名称',
    ceUrl: '搜索 URL',
    ceIconDefault: '搜索引擎图标 (SVG)',
    btnCancel: '取消',
    btnAdd: '添加',
    btnUpdate: '更新',
    btnDelete: '删除',
    btnManualAdd: '手动添加',

    btnResetAll: '恢复默认设置',
    moreBackup: '备份与恢复',
    moreReset: '重置',
    btnExportConfig: '导出配置',
    btnImportConfig: '导入配置',
    toastExportSuccess: '配置已导出',
    toastImportSuccess: '配置已导入，即将刷新页面',
    toastImportFailed: '导入失败，请检查文件格式',
    currentWallpaper: '当前',
    confirmDeleteWallpaper: '确定要删除此壁纸吗?',
    wpSourceNone: '无',
    wpSourceLocal: '本地壁纸',
    wpSourceBing: 'Bing壁纸',

    historyTitle: '搜索历史',
    clearHistory: '清除历史记录',

    wallpaperManage: '壁纸管理',
    importWallpaper: '导入本地壁纸',
    wallpaperRotateEdit: '壁纸轮换',
    restoreDefault: '恢复默认',
    clearAll: '清空',
    btnClose: '关闭',
    noHistoryWallpaper: '暂无历史壁纸',

    switchWallpaper: '切换壁纸',
    contextSettings: '设置',

    engineBing: '必应',
    engineBaidu: '百度',

    toastSwitchSuccess: '切换成功',
    toastWallpaperInUse: '该壁纸正在使用',
    toastRotateUpdated: '轮换列表已更新',
    toastImportSuccess: '导入成功',
    toastStorageFull: '存储空间不足',
    toastFileReadError: '文件读取异常',
    toastCannotReadFile: '无法读取文件',
    toastSelectImage: '请选择图片文件',
    toastRestored: '已恢复',
    toastCleared: '已清空',
    toastConfigPoolFirst: '请先配置轮换池',
    toastRotated: '已轮换',
    toastFillNameUrl: '请填写名称和搜索 URL',
    toastSelectIcon: '请选择搜索引擎图标',
    toastNameExists: '该名称已存在',
    toastUrlDuplicate: '该 URL 已被「{name}」使用',
    toastDeleteSuccess: '删除成功',
    toastUpdateSuccess: '更新成功「{name}」',
    toastAddSuccess: '添加成功「{name}」',
    toastDefaultEngineLocked: '当前默认引擎无法关闭',
    toastSettingsReset: '设置已恢复默认',
    toastSearchReset: '搜索框已重置',
    toastNeedTwoWallpapers: '至少需要两张壁纸才能切换',
    toastWallpaperSwitched: '已切换壁纸',
    toastWallpaperNotEnabled: '当前未启用壁纸，无法切换',
    toastSelectSvg: '请选择 SVG 格式图标',
    toastIconTooLarge: '图标文件过大，请选择小于 512KB 的文件',
    toastIconReadFailed: '图标读取失败',

    confirmReset: '确定将所有设置恢复为默认值吗？\n此操作将清除壁纸、主题色、自定义引擎等所有更改，且不可撤销。',
    btnConfirm: '确认',

    transTitle: '翻译',
    transInputPlaceholder: '输入要翻译的文本...',
    transSwapTitle: '调换源语言与目标语言',
    transClearTitle: '清空输入',
    transDetect: '自动检测',
    transTranslating: '翻译中…',
    transError: '翻译失败，请重试',
    transResultLabel: '翻译结果',
    transSettingsTitle: '翻译设置',
    transSettingsClose: '关闭设置',
    transSettingsEngine: '翻译引擎',
    transSettingsKey: 'API Key',
    transSettingsRegion: '区域',
    transRegionNone: '全局',
    transNeedKey: '请先在设置中填写 API Key',
    transEngineBing: 'Microsoft（非官方）',
    transEngineCustom: '自定义 (OpenAI 兼容)',
    transCustomUrl: 'API 地址',
    transCustomUrlPlaceholder: 'https://api.deepseek.com/v1',
    transCustomModel: '模型名',
    transCustomModelPlaceholder: 'deepseek-chat',
    transCustomPrompt: '系统提示词（可选，可用 {source}/{target}）',
    transNeedConfig: '请先在设置中填写自定义引擎配置',
    transFetchModels: '获取模型列表',
    transModelLoading: '加载中…',
    transModelNeedUrlKey: '请先填写 API 地址和 Key',
    transModelFetchFailed: '获取模型列表失败',
    transModelAuthFailed: 'API Key 无效或无权限',
    transModelNotSupported: '该服务不支持列出模型，可手动输入模型名',

    popupTitle: 'Minimal Tab',
    popupOpenPanel: '打开翻译边栏',
    popupTranslatePage: '翻译此页',
    popupCancelTranslate: '取消翻译',

    sectionPageTrans: '网页翻译',
    pageTransTarget: '目标语言',
    pageTransFollowSidebar: '跟随边栏翻译',
    pageTransBall: '悬浮球',
    pageTransMode: '呈现方式',
    pageTransModeReplace: '仅译文',
    pageTransModeBilingual: '双语对照',

    langZhCn: '中文',
    langZhTw: '繁体中文',
    langEn: '英语',
    langJa: '日语',
    langKo: '韩语',
    langFr: '法语',
    langDe: '德语',
    langEs: '西班牙语',
    langRu: '俄语',
    langIt: '意大利语',
    langPt: '葡萄牙语',
    langVi: '越南语',
    langTh: '泰语',
    langAr: '阿拉伯语',
    langHi: '印地语',
    langNl: '荷兰语',
    langPl: '波兰语',
    langTr: '土耳其语',
    langSv: '瑞典语',
    langDa: '丹麦语',
    langFi: '芬兰语',
    langNo: '挪威语',
    langEl: '希腊语',
    langCs: '捷克语',
    langHu: '匈牙利语',
    langRo: '罗马尼亚语',
    langUk: '乌克兰语',
    langId: '印度尼西亚语',
    langMs: '马来语',
    langFil: '菲律宾语',
    langBn: '孟加拉语',
    langUr: '乌尔都语',
    langFa: '波斯语',
    langHe: '希伯来语',
    langTa: '泰米尔语',
    langTe: '泰卢固语',
    langMl: '马拉雅拉姆语',
    langKn: '卡纳达语',
    langMr: '马拉地语',
    langPa: '旁遮普语',
    langSw: '斯瓦希里语',
  },

  'en': {
    pageTitle: 'Minimal Tab',
    searchPlaceholder: 'Type to search...',
    settingsTitle: 'Settings',
    settingsHeader: 'Settings',

    navTheme: 'Theme',
    navEngines: 'Search',
    navPersonalize: 'Personalize',
    navAbout: 'About',
    navMore: 'More',
    aboutVersion: 'Version',
    aboutProject: 'Project',
    aboutFeedback: 'Feedback',
    aboutPrivacy: 'Privacy Policy',
    aboutLicense: 'Licensed under MIT',
    colorPicker: 'Color Picker',

    sectionAppearance: 'Appearance',
    themeSystem: 'System',
    themeLight: 'Light',
    themeDark: 'Dark',
    sectionAccentColor: 'Accent Color',
    sectionWallpaper: 'Wallpaper',

    wallpaperOverlay: 'Overlay',
    wallpaperBlur: 'Blur',
    wallpaperRotate: 'Rotation',
    rotateNow: 'Rotate Now',
    rotateOff: 'No Rotation',
    rotate1h: 'Every 1 Hour',
    rotate6h: 'Every 6 Hours',
    rotate12h: 'Every 12 Hours',
    rotate24h: 'Every 24 Hours',

    sectionSidebar: 'Sidebar',
    sectionClock: 'Clock',
    clockColor: 'Clock Color',
    sidebarOpacity: 'Opacity',
    sidebarFrosted: 'Frosted Glass',
    digitalClock: 'Digital Clock',
    followSearch: 'Follow Search Box',
    clockPosition: 'Clock Position',
    clockBelow: 'Below Search',
    clockAbove: 'Above Search',
    clockLeftTop: 'Top Left',
    clockRightTop: 'Top Right',
    clockCenter: 'Center',
    clockLeftBottom: 'Bottom Left',
    clockRightBottom: 'Bottom Right',
    clockCustom: 'Custom',
    clockCustomX: 'X',
    clockCustomY: 'Y',
    sectionLanguage: 'Language',

    sectionSearchBox: 'Search Box',
    enableSearchBox: 'Enable Search Box',
    searchOffsetY: 'Vertical Offset',
    searchOffsetX: 'Horizontal Offset',
    searchWidth: 'Width',
    searchRadius: 'Border Radius',
    sectionEngines: 'Search Engines',
    sectionDefaultEngine: 'Default Engine',
    searchHistory: 'Search History',
    openInNewTab: 'Open results in new tab',
    suggestionProvider: 'Search Suggestions',
    suggestionOff: 'Off',
    suggestionBaidu: 'Baidu',
    suggestionGoogle: 'Google',
    suggestionBing: 'Bing',
    suggestionTitle: 'Suggestions',

    addCustomEngine: 'Add Custom Engine',
    editCustomEngine: 'Edit Custom Engine',
    ceName: 'Name',
    ceNamePlaceholder: 'Engine name',
    ceUrl: 'Search URL',
    ceIconDefault: 'Search Engine Icon (SVG)',
    btnCancel: 'Cancel',
    btnAdd: 'Add',
    btnUpdate: 'Update',
    btnDelete: 'Delete',
    btnManualAdd: 'Add Manually',

    btnResetAll: 'Reset All Settings',
    moreBackup: 'Backup & Restore',
    moreReset: 'Reset',
    btnExportConfig: 'Export Config',
    btnImportConfig: 'Import Config',
    toastExportSuccess: 'Configuration exported',
    toastImportSuccess: 'Configuration imported, reloading...',
    toastImportFailed: 'Import failed, check file format',
    currentWallpaper: 'Current',
    confirmDeleteWallpaper: 'Delete this wallpaper?',
    wpSourceNone: 'None',
    wpSourceLocal: 'Local',
    wpSourceBing: 'Bing',

    historyTitle: 'Search History',
    clearHistory: 'Clear History',

    wallpaperManage: 'Wallpaper Manager',
    importWallpaper: 'Import Local Wallpaper',
    wallpaperRotateEdit: 'Rotation',
    restoreDefault: 'Restore Default',
    clearAll: 'Clear All',
    btnClose: 'Close',
    noHistoryWallpaper: 'No wallpaper history',

    switchWallpaper: 'Switch Wallpaper',
    contextSettings: 'Settings',

    engineBing: 'Bing',
    engineBaidu: 'Baidu',

    toastSwitchSuccess: 'Switched successfully',
    toastWallpaperInUse: 'This wallpaper is currently in use',
    toastRotateUpdated: 'Rotation list updated',
    toastImportSuccess: 'Import successful',
    toastStorageFull: 'Insufficient storage space',
    toastFileReadError: 'File read error',
    toastCannotReadFile: 'Cannot read file',
    toastSelectImage: 'Please select an image file',
    toastRestored: 'Restored',
    toastCleared: 'Cleared',
    toastConfigPoolFirst: 'Please configure the rotation pool first',
    toastRotated: 'Rotated',
    toastFillNameUrl: 'Please fill in name and search URL',
    toastSelectIcon: 'Please select a search engine icon',
    toastNameExists: 'This name already exists',
    toastUrlDuplicate: 'This URL is already used by "{name}"',
    toastDeleteSuccess: 'Deleted successfully',
    toastUpdateSuccess: 'Updated "{name}"',
    toastAddSuccess: 'Added "{name}"',
    toastDefaultEngineLocked: 'Cannot disable the current default engine',
    toastSettingsReset: 'Settings restored to defaults',
    toastSearchReset: 'Search box reset',
    toastNeedTwoWallpapers: 'At least two wallpapers needed to switch',
    toastWallpaperSwitched: 'Wallpaper switched',
    toastWallpaperNotEnabled: 'No wallpaper enabled',
    toastSelectSvg: 'Please select an SVG icon',
    toastIconTooLarge: 'Icon file too large, please select a file under 512KB',
    toastIconReadFailed: 'Failed to read icon',

    confirmReset: 'Are you sure you want to reset all settings to defaults?\nThis will clear wallpaper, accent color, custom engines, and all other changes. This action cannot be undone.',
    btnConfirm: 'Confirm',

    transTitle: 'Translate',
    transInputPlaceholder: 'Type text to translate...',
    transSwapTitle: 'Swap source and target language',
    transClearTitle: 'Clear input',
    transDetect: 'Auto detect',
    transTranslating: 'Translating…',
    transError: 'Translation failed, please retry',
    transResultLabel: 'Translation Result',
    transSettingsTitle: 'Translation Settings',
    transSettingsClose: 'Close settings',
    transSettingsEngine: 'Translation Engine',
    transSettingsKey: 'API Key',
    transSettingsRegion: 'Region',
    transRegionNone: 'Global',
    transNeedKey: 'Please set your API key in Settings first',
    transEngineBing: 'Microsoft (Unofficial)',
    transEngineCustom: 'Custom (OpenAI-compatible)',
    transCustomUrl: 'API Base URL',
    transCustomUrlPlaceholder: 'https://api.openai.com/v1',
    transCustomModel: 'Model',
    transCustomModelPlaceholder: 'gpt-4o-mini',
    transCustomPrompt: 'System prompt (optional, {source}/{target} supported)',
    transNeedConfig: 'Please configure the custom engine in Settings first',
    transFetchModels: 'Fetch models',
    transModelLoading: 'Loading…',
    transModelNeedUrlKey: 'Set API Base URL and Key first',
    transModelFetchFailed: 'Failed to fetch models',
    transModelAuthFailed: 'API Key invalid or no permission',
    transModelNotSupported: 'This service does not support listing models, please type the model name manually',

    popupTitle: 'Minimal Tab',
    popupOpenPanel: 'Open Translator',
    popupTranslatePage: 'Translate This Page',
    popupCancelTranslate: 'Cancel Translation',

    sectionPageTrans: 'Web Page Translation',
    pageTransTarget: 'Target Language',
    pageTransFollowSidebar: 'Follow Sidebar Translation',
    pageTransBall: 'Floating Button',
    pageTransMode: 'Presentation Mode',
    pageTransModeReplace: 'Translation Only',
    pageTransModeBilingual: 'Bilingual',

    langZhCn: 'Chinese',
    langZhTw: 'Traditional Chinese',
    langEn: 'English',
    langJa: 'Japanese',
    langKo: 'Korean',
    langFr: 'French',
    langDe: 'German',
    langEs: 'Spanish',
    langRu: 'Russian',
    langIt: 'Italian',
    langPt: 'Portuguese',
    langVi: 'Vietnamese',
    langTh: 'Thai',
    langAr: 'Arabic',
    langHi: 'Hindi',
    langNl: 'Dutch',
    langPl: 'Polish',
    langTr: 'Turkish',
    langSv: 'Swedish',
    langDa: 'Danish',
    langFi: 'Finnish',
    langNo: 'Norwegian',
    langEl: 'Greek',
    langCs: 'Czech',
    langHu: 'Hungarian',
    langRo: 'Romanian',
    langUk: 'Ukrainian',
    langId: 'Indonesian',
    langMs: 'Malay',
    langFil: 'Filipino',
    langBn: 'Bengali',
    langUr: 'Urdu',
    langFa: 'Persian',
    langHe: 'Hebrew',
    langTa: 'Tamil',
    langTe: 'Telugu',
    langMl: 'Malayalam',
    langKn: 'Kannada',
    langMr: 'Marathi',
    langPa: 'Punjabi',
    langSw: 'Swahili',
  }
};

window.I18N_CURRENT = localStorage.getItem('language') || 'zh-CN';

function t(key, vars) {
  const map = window.I18N_DATA[window.I18N_CURRENT] || window.I18N_DATA['zh-CN'];
  let text = map[key];
  if (text === undefined) return key;
  if (vars) {
    Object.keys(vars).forEach(k => {
      text = text.replace('{' + k + '}', vars[k]);
    });
  }
  return text;
}

function setLanguage(lang) {
  window.I18N_CURRENT = lang;
  localStorage.setItem('language', lang);
  document.documentElement.lang = lang;

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (key) el.textContent = t(key);
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (key) el.placeholder = t(key);
  });
  document.querySelectorAll('[data-i18n-title]').forEach(el => {
    const key = el.getAttribute('data-i18n-title');
    if (key) el.title = t(key);
  });

  const seg = document.getElementById('languageSeg');
  if (seg) {
    seg.querySelectorAll('.theme-mode-opt').forEach(b => {
      b.classList.toggle('active', b.dataset.lang === lang);
    });
  }

  if (window.refreshI18n) window.refreshI18n();
}

function initLanguage() {
  const saved = localStorage.getItem('language') || 'zh-CN';
  setLanguage(saved);
}

document.addEventListener('DOMContentLoaded', initLanguage);
